### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tscpp** [tscpp/knuckles#2]
Continues from [kolint/next#1](https://github.com/kolint/next/issues/1).

### Analyzer

- [x] Catch parsing errors in analyzer and report them as issues.
- [x] #3
- [x] #19
- [x] #27
- [x] #31 

### SSR

- [x] Allow to explicitly disable rendering with `no-ssr` directive.

### TypeScript

- [x] #5
- [x] Asserting the type of $parent/$parents [kolint/next#335](https://github.com/kolint/kolint/issues/335)
- [x] #9

### Parser

- [x] #4 
- [x] #17 

### Documentation

- [x] Update syntax for analyzer
- [x] #14 
- [x] Docs is broken after added playground
- [x] Fix releases
- [x] Update docs for new syntax
- [x] README banner text should be converted to path
- [x] #44 (coveralls)
- [x] #43 

## Stage 4

- [ ] Implement formatter

### Analyzer

- [ ] #65
- [ ] #66
  - [ ] Rule for untyped $context with quick fix when automatic resolution is configured.
- [ ] #67
  - [ ] Shared context deconstruction for descendants.
  - [ ] Optional context transformation.
  - [ ] Preserve context when identical child binding context.

### TypeScript

- [x] Allow user to override default interop algorithm for view models.
- [ ] #68

### SSR

- [ ] #70
- [ ] Improve SSR CLI

### Analyzer

- [ ] #71

### TypeScript

- [ ] #69

### Language Features

- [x] Go to Definition
- [x] Hover
- [x] Completion
- [x] Diagnostics
- [ ] Go to Declaration
- [ ] Go to Type Definition
- [ ] Go to Implementation
- [ ] Find References
- [ ] Document Highlight
- [ ] Document Symbols
- [ ] Semantic Tokens
- [ ] Code Action
- [ ] Rename
- [ ] Document Link
- [ ] Inline Value
- [ ] Inlay Hint
- [ ] Signature Help
- [ ] Formatting
- [ ] Linked Editing Range

**Comment by tscpp** [comment]
cc @ondrejmirtes @maskmaster
